### PR TITLE
Tow 55 create opportunity dao

### PR DESCRIPTION
**Pull request by RYeeAnn**
-Registered Opportunity to admin.
-Created Opportunity class in Dao.py and added def for create_opportunity.
-Added Opportunity model
-Added OpportunityServices class in services.py
-Added Opportunity migrations
-Added Opportunity dataclass in types.py
-Added test case for create_opportunity

### CODE REVIEW

**Comment by GagenvirGill** [comment]
Some of the recent merges are reversed in this, such as the ones regarding the volunteer model fields update and the subsequent files changed.

**Comment by RYeeAnn** [comment]
> Some of the recent merges are reversed in this, such as the ones regarding the volunteer model fields update and the subsequent files changed. Other than that, the changes look good though!

Ah i see, regarding the changes from name -> first_name and last_name correct? In addition to that, i've updated types.py to have first_name and last_name instead of just name.

**Comment by GagenvirGill** [comment]
> > Some of the recent merges are reversed in this, such as the ones regarding the volunteer model fields update and the subsequent files changed. Other than that, the changes look good though!
> 
> Ah i see, regarding the changes from name -> first_name and last_name correct? In addition to that, i've updated types.py to have first_name and last_name instead of just name.

Yep, looks great!

**Review by GagenvirGill — APPROVED** [review]

**Review by ansel-rangers11 — APPROVED** [review]
Looks good, no issues with main branch, wel ldone

**Pull request merged**
